# Generated by Django 2.0.7 on 2018-07-27 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '勋章',
                'verbose_name_plural': '勋章',
            },
        ),
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='标题')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('icon', models.ImageField(upload_to='', verbose_name='图标')),
                ('icon2x', models.ImageField(upload_to='', verbose_name='图标@2x')),
            ],
            options={
                'verbose_name': '勋章类型',
                'verbose_name_plural': '勋章类型',
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.BadgeType', verbose_name='勋章'),
        ),
    ]
