# Generated by Django 2.1.2 on 2018-10-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildbadge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='badge.BadgeType', verbose_name='勋章类型'),
        ),
        migrations.AlterField(
            model_name='playerbadge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='badge.BadgeType', verbose_name='勋章类型'),
        ),
    ]
