# Generated by Django 2.1.2 on 2018-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(help_text='描述', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(help_text='图标', upload_to='', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon2x',
            field=models.ImageField(help_text='图标@2x', upload_to='', verbose_name='图标@2x'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='title',
            field=models.CharField(help_text='标题', max_length=50, unique=True, verbose_name='标题'),
        ),
    ]
