# Generated by Django 2.1.2 on 2018-10-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_auto_20181009_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildbadge',
            old_name='created',
            new_name='acquiredAt',
        ),
        migrations.RenameField(
            model_name='playerbadge',
            old_name='created',
            new_name='acquiredAt',
        ),
    ]
