# Generated by Django 2.1.2 on 2018-10-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unlocked',
            options={'verbose_name': '解锁', 'verbose_name_plural': '解锁'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(auto_now_add=True, help_text='日期', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement',
            field=models.SlugField(help_text='成就', max_length=256, verbose_name='成就'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='player',
            field=models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='player.Player', verbose_name='玩家'),
        ),
        migrations.AlterField(
            model_name='unlocked',
            name='item',
            field=models.SlugField(help_text='解锁项目', max_length=256, verbose_name='解锁项目'),
        ),
        migrations.AlterField(
            model_name='unlocked',
            name='player',
            field=models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='player.Player', verbose_name='玩家'),
        ),
        migrations.AlterField(
            model_name='unlocked',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='日期', verbose_name='日期'),
        ),
    ]
