# Generated by Django 2.1.2 on 2018-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='正文', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.SlugField(help_text='版本', max_length=20, primary_key=True, serialize=False, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='version',
            name='testing',
            field=models.BooleanField(default=False, help_text='显示测试服入口', verbose_name='显示测试服入口'),
        ),
        migrations.AlterField(
            model_name='version',
            name='url',
            field=models.FileField(help_text='更新文件', upload_to='', verbose_name='更新文件'),
        ),
    ]
