# Generated by Django 2.1.2 on 2018-10-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.SlugField(max_length=20, verbose_name='类型')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
            ],
            options={
                'verbose_name': '交易中的道具',
                'verbose_name_plural': '交易中的道具',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.SlugField(max_length=20, verbose_name='类型')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具',
            },
        ),
        migrations.CreateModel(
            name='ItemActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.SlugField(max_length=20, verbose_name='动作')),
                ('extra', models.CharField(max_length=256, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='item.Item', verbose_name='道具')),
            ],
            options={
                'verbose_name': '道具动作历史',
                'verbose_name_plural': '道具动作历史',
            },
        ),
    ]
