# Generated by Django 2.0.7 on 2018-08-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
            ],
            options={
                'verbose_name': '交易中的道具',
                'verbose_name_plural': '交易中的道具',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.SlugField(max_length=20, verbose_name='类型')),
                ('arg', models.IntegerField(default=0, verbose_name='参数')),
                ('status', models.SlugField(max_length=20, verbose_name='类型')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具',
            },
        ),
        migrations.CreateModel(
            name='ItemActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.SlugField(max_length=20, verbose_name='动作')),
                ('extra', models.CharField(max_length=256, verbose_name='额外数据')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='item.Item', verbose_name='道具')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='相关用户')),
            ],
            options={
                'verbose_name': '道具动作历史',
                'verbose_name_plural': '道具动作历史',
            },
        ),
        migrations.AddField(
            model_name='exchange',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='item.Item', verbose_name='道具'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
    ]
