# Generated by Django 2.0.7 on 2018-08-08 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='arg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='exchange',
            name='type',
            field=models.SlugField(default=django.utils.timezone.now, max_length=20, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
