# Generated by Django 2.1.2 on 2018-10-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20181013_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemactivity',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemactivity',
            name='player',
        ),
        migrations.AlterField(
            model_name='exchange',
            name='price',
            field=models.PositiveIntegerField(help_text='价格', verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='seller',
            field=models.ForeignKey(help_text='卖家', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='player.Player', verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='type',
            field=models.SlugField(help_text='类型', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.Player', verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.SlugField(help_text='类型', max_length=20, verbose_name='类型'),
        ),
        migrations.DeleteModel(
            name='ItemActivity',
        ),
    ]
