# Generated by Django 2.1.2 on 2018-10-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20181012_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemactivity',
            old_name='created',
            new_name='created_at',
        ),
    ]
