# Generated by Django 2.0.7 on 2018-08-08 14:32

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='手机号')),
                ('verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('ppoint', models.IntegerField(verbose_name='P点')),
                ('jiecao', models.IntegerField(verbose_name='节操')),
                ('games', models.IntegerField(verbose_name='游戏数')),
                ('drops', models.IntegerField(verbose_name='逃跑数')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='称号')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '玩家资料',
                'verbose_name_plural': '玩家资料',
            },
        ),
    ]
