# Generated by Django 2.0.7 on 2018-08-08 17:35

from django.db import migrations, models
import player.models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[player.models.is_phone_number], verbose_name='手机号'),
        ),
    ]
