# Generated by Django 2.1.2 on 2018-10-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='badges',
            field=models.ManyToManyField(related_name='players', to='badge.Badge', verbose_name='勋章'),
        ),
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='guild.Guild', verbose_name='势力'),
        ),
    ]
