# Generated by Django 2.1.2 on 2018-10-14 03:24

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import player.models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='drops',
            field=models.IntegerField(help_text='逃跑数', verbose_name='逃跑数'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='games',
            field=models.IntegerField(help_text='游戏数', verbose_name='游戏数'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='jiecao',
            field=models.IntegerField(help_text='节操', verbose_name='节操'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='player',
            field=annoying.fields.AutoOneToOneField(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='玩家'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='ppoint',
            field=models.IntegerField(help_text='P点', verbose_name='P点'),
        ),
        migrations.AlterField(
            model_name='player',
            name='badges',
            field=models.ManyToManyField(help_text='勋章', related_name='players', to='badge.Badge', verbose_name='勋章'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(blank=True, help_text='签名', max_length=150, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='player',
            name='blocks',
            field=models.ManyToManyField(help_text='黑名单', related_name='_player_blocks_+', to='player.Player', verbose_name='黑名单'),
        ),
        migrations.AlterField(
            model_name='player',
            name='forum_id',
            field=models.IntegerField(blank=True, help_text='论坛ID', null=True, unique=True, verbose_name='论坛ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(help_text='好友', related_name='_player_friends_+', to='player.Player', verbose_name='好友'),
        ),
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(blank=True, help_text='势力', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='guild.Guild', verbose_name='势力'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(help_text='昵称', max_length=150, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=annoying.fields.AutoOneToOneField(help_text='关联用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='加入日期', verbose_name='加入日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='手机号', max_length=15, unique=True, validators=[player.models.is_phone_number], verbose_name='手机号'),
        ),
    ]
