# Generated by Django 2.1.2 on 2018-10-17 14:27

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20181014_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='id',
        ),
        migrations.AlterField(
            model_name='credit',
            name='drops',
            field=models.IntegerField(default=0, help_text='逃跑数', verbose_name='逃跑数'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='games',
            field=models.IntegerField(default=0, help_text='游戏数', verbose_name='游戏数'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='jiecao',
            field=models.IntegerField(default=0, help_text='节操', verbose_name='节操'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='player',
            field=annoying.fields.AutoOneToOneField(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='player.Player', verbose_name='玩家'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='ppoint',
            field=models.IntegerField(default=0, help_text='P点', verbose_name='P点'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(help_text='关联用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
