# Generated by Django 2.1.2 on 2018-10-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20181017_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.URLField(blank=True, help_text='头像', max_length=150, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='player',
            field=models.OneToOneField(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='player.Player', verbose_name='玩家'),
        ),
    ]
