# Generated by Django 2.1.2 on 2018-10-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20181018_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='forum_name',
            field=models.IntegerField(blank=True, help_text='论坛昵称', null=True, unique=True, verbose_name='论坛昵称'),
        ),
        migrations.AlterField(
            model_name='player',
            name='blocks',
            field=models.ManyToManyField(blank=True, help_text='黑名单', related_name='blocked_by', to='player.Player', verbose_name='黑名单'),
        ),
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, help_text='好友', related_name='friended_by', to='player.Player', verbose_name='好友'),
        ),
    ]
