# Generated by Django 2.1.2 on 2018-10-22 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20181018_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='原因', max_length=150, verbose_name='原因')),
                ('game_id', models.IntegerField(blank=True, help_text='游戏ID', null=True, verbose_name='游戏ID')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, help_text='举报时间', verbose_name='举报时间')),
                ('is_processed', models.BooleanField(default=False, help_text='已经处理', verbose_name='已经处理')),
            ],
        ),
        migrations.RemoveField(
            model_name='credit',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='drops',
            field=models.IntegerField(default=0, help_text='逃跑数', verbose_name='逃跑数'),
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.IntegerField(default=0, help_text='游戏数', verbose_name='游戏数'),
        ),
        migrations.AddField(
            model_name='player',
            name='jiecao',
            field=models.IntegerField(default=0, help_text='节操', verbose_name='节操'),
        ),
        migrations.AddField(
            model_name='player',
            name='ppoint',
            field=models.IntegerField(default=0, help_text='P点', verbose_name='P点'),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.OneToOneField(help_text='报告者', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='player.Player', verbose_name='举报者'),
        ),
        migrations.AddField(
            model_name='report',
            name='suspect',
            field=models.OneToOneField(help_text='嫌疑人', on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='player.Player', verbose_name='嫌疑人'),
        ),
    ]
