# Generated by Django 2.1.2 on 2018-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20181022_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '举报', 'verbose_name_plural': '举报'},
        ),
        migrations.AlterField(
            model_name='player',
            name='forum_name',
            field=models.CharField(blank=True, help_text='论坛昵称', max_length=150, null=True, unique=True, verbose_name='论坛昵称'),
        ),
    ]
