# Generated by Django 2.1.2 on 2018-10-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_auto_20181023_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'permissions': (('change_credit', '可以修改积分'),), 'verbose_name': '玩家', 'verbose_name_plural': '玩家'},
        ),
    ]
