# Generated by Django 2.1.2 on 2018-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20181023_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='detail',
            field=models.TextField(default='-', help_text='原因', verbose_name='详情'),
            preserve_default=False,
        ),
    ]
