# Generated by Django 2.1.2 on 2018-10-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_report_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='report',
            name='outcome',
            field=models.CharField(blank=True, help_text='处理结果', max_length=150, null=True, verbose_name='处理结果'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(help_text='原因', max_length=10, verbose_name='原因'),
        ),
    ]
