# Generated by Django 2.1.2 on 2018-10-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friend', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.Player', verbose_name='好友'),
        ),
        migrations.AddField(
            model_name='friend',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.Player', verbose_name='玩家'),
        ),
        migrations.AddField(
            model_name='block',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='player.Player', verbose_name='拉黑'),
        ),
        migrations.AddField(
            model_name='block',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.Player', verbose_name='玩家'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('player', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('player', 'block')},
        ),
    ]
