# Generated by Django 2.1.2 on 2018-10-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20181012_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='created',
            new_name='blocked_at',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='created',
            new_name='followed_at',
        ),
    ]
