# Generated by Django 2.1.2 on 2018-10-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('slogan', models.CharField(max_length=200, verbose_name='口号')),
                ('totem', models.ImageField(blank=True, upload_to='', verbose_name='图腾')),
                ('founded_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '势力',
                'verbose_name_plural': '势力',
            },
        ),
    ]
