# Generated by Django 2.0.7 on 2018-08-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('slogan', models.CharField(max_length=200, verbose_name='口号')),
                ('totem', models.ImageField(blank=True, upload_to='', verbose_name='图腾')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_guilds', to=settings.AUTH_USER_MODEL, verbose_name='创始人')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading_guilds', to=settings.AUTH_USER_MODEL, verbose_name='领袖')),
            ],
            options={
                'verbose_name': '势力',
                'verbose_name_plural': '势力',
            },
        ),
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joined', models.DateTimeField(auto_now_add=True, verbose_name='加入日期')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='guild.Guild', verbose_name='势力')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '势力成员',
                'verbose_name_plural': '势力成员',
            },
        ),
    ]
