# Generated by Django 2.0.7 on 2018-08-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='created',
            new_name='founded',
        ),
    ]
