# Generated by Django 2.1.2 on 2018-10-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guild', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_guilds', to='player.Player', verbose_name='创始人'),
        ),
        migrations.AddField(
            model_name='guild',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leading_guild', to='player.Player', verbose_name='领袖'),
        ),
        migrations.AddField(
            model_name='guild',
            name='requests',
            field=models.ManyToManyField(related_name='requested_guilds', to='player.Player', verbose_name='申请列表'),
        ),
    ]
