# Generated by Django 2.1.2 on 2018-10-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
        ('guild', '0002_auto_20181012_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='badges',
            field=models.ManyToManyField(related_name='guilds', to='badge.Badge'),
        ),
    ]
