# Generated by Django 2.1.2 on 2018-10-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_auto_20181013_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='badges',
            field=models.ManyToManyField(help_text='勋章', related_name='guilds', to='badge.Badge', verbose_name='勋章'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='founded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='founder',
            field=models.ForeignKey(help_text='创始人', on_delete=django.db.models.deletion.CASCADE, related_name='founded_guilds', to='player.Player', verbose_name='创始人'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='leader',
            field=models.OneToOneField(help_text='领袖', on_delete=django.db.models.deletion.CASCADE, related_name='leading_guild', to='player.Player', verbose_name='领袖'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(help_text='名称', max_length=20, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='requests',
            field=models.ManyToManyField(help_text='申请列表', related_name='requested_guilds', to='player.Player', verbose_name='申请列表'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='slogan',
            field=models.CharField(help_text='口号', max_length=200, verbose_name='口号'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='totem',
            field=models.ImageField(blank=True, help_text='图腾', upload_to='', verbose_name='图腾'),
        ),
    ]
