# Generated by Django 2.0.7 on 2018-08-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_auto_20180809_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildmember',
            old_name='member',
            new_name='user',
        ),
    ]
