# Generated by Django 2.1.2 on 2018-10-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_auto_20180809_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='founded',
            new_name='foundedAt',
        ),
        migrations.RenameField(
            model_name='guildmember',
            old_name='joined',
            new_name='joinedAt',
        ),
    ]
